apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-ruggine-token
  namespace: ruggine
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-ruggine-token
    namespace: ruggine
  project: spidamar
  config: prd
  secrets:
    - DOPPLER_RUGGINE_TOKEN
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: ruggine-ghcr-secret
  namespace: doppler-operator-system
  labels:
    app.kubernetes.io/name: ruggine
    app.kubernetes.io/part-of: url-shortener
spec:
  tokenSecret:
    name: doppler-ruggine-token
    namespace: ruggine
  managedSecret:
    name: ghcr-secret
    namespace: ruggine
    type: kubernetes.io/dockerconfigjson
  project: ruggine
  config: prd
  secrets:
    - RUGGINE_GHCR_DOCKER_CONFIG_TOKEN
  processors:
    RUGGINE_GHCR_DOCKER_CONFIG_TOKEN:
      asName: .dockerconfigjson
