apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ruggine-prod
  namespace: flux-system
spec:
  dependsOn:
    - name: ruggine-base
  interval: 1m
  path: ./infra/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: ruggine
