apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ruggine-staging
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: ruggine
