apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruggine
  namespace: ruggine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruggine
  template:
    metadata:
      labels:
        app: ruggine
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: ruggine
        image: ghcr.io/gurghet/ruggine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: TZ
          value: "Europe/Rome"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: ruggine-service
  namespace: ruggine
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ruggine
