apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
- ../../base

patches:
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: ruggine

commonLabels:
  environment: prod

images:
- name: ghcr.io/gurghet/ruggine
  newTag: 3d1c771815c2f287303bbf20ae233ca77e7c14e4
