apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
- name: ghcr.io/gurghet/ruggine
  newTag: latest  # This will be updated by Flux when deploying to prod
