apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruggine
  namespace: ruggine
spec:
  tls:
  - hosts:
    - codecraft.engineering
    secretName: prod-codecraft-engineering-tls
  rules:
  - host: codecraft.engineering
    http:
      paths:
      - backend:
          service:
            name: prod-ruggine-service
