apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

resources:
- ../../base

patches:
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: ruggine

commonLabels:
  environment: staging

images:
- name: ghcr.io/gurghet/ruggine
  newTag: 44366986465931a58dde32b5eb91dc2a8486ef66
