apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

resources:
- ../../base

patches:
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: ruggine
images:
- name: ghcr.io/gurghet/ruggine
  newTag: 2847f5be80da2a114c8b121c1b4574670b4357f0
