apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

resources:
- ../../base

patches:
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: ruggine

commonLabels:
  environment: staging

images:
- name: ghcr.io/gurghet/ruggine
  newTag: 6e12d29b33a224276fec86cccf5cf7ec7512476a
