apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
images:
- name: ghcr.io/gurghet/ruggine
  newTag: 8d759cf29bba0c4d9ab805082e1939054cb7138a
