apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruggine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruggine-staging
  template:
    metadata:
      labels:
        app: ruggine-staging

---
apiVersion: v1
kind: Service
metadata:
  name: ruggine-service
spec:
  selector:
    app: ruggine-staging

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruggine-ingress
spec:
  tls:
  - hosts:
    - staging.codecraft.engineering
    secretName: staging-codecraft-engineering-tls
  rules:
  - host: staging.codecraft.engineering
    http:
      paths:
      - path: /url
        pathType: Prefix
        backend:
          service:
            name: ruggine-service
            port:
              name: http
