name: E2E Tests and Production Promotion

on:
  # Triggered by the docker-deploy workflow
  workflow_run:
    workflows: ["Build and Deploy Docker Image"]
    types:
      - completed
    branches:
      - master

permissions:
  contents: write

jobs:
  e2e-test:
    runs-on: ubuntu-24.04-arm
    # Only run if the docker-deploy workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Wait for staging deployment
        run: |
          # Debug information
          echo "Workflow run id: ${{ github.event.workflow_run.id }}"
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Workflow sha: ${{ github.event.workflow_run.head_sha }}"
          echo "Current sha: ${{ github.sha }}"
          
          # Get the SHA of the docker-deploy workflow that triggered this
          EXPECTED_VERSION="${{ github.event.workflow_run.head_sha }}"
          echo "Waiting for version $EXPECTED_VERSION to be deployed..."
          
          # Wait up to 2 minutes for staging to be ready with correct version
          for i in {1..24}; do
            RESPONSE=$(curl -s -k https://staging.codecraft.engineering/version)
            if [ $? -eq 0 ]; then
              CURRENT_VERSION=$(echo "$RESPONSE" | jq -r '.version')
              if [ "$CURRENT_VERSION" = "$EXPECTED_VERSION" ]; then
                echo " Staging environment is ready with correct version!"
                exit 0
              fi
              echo " Wrong version: expected $EXPECTED_VERSION, got $CURRENT_VERSION"
            fi
            echo "Waiting for staging environment to be ready... ($i/24)"
            sleep 5
          done
          echo "Staging environment not ready with correct version after 2 minutes"
          exit 1

      - name: Run E2E Tests
        run: |
          ./e2e-scripts/tests.sh

      - name: Notify E2E Success
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"❌ Ruggine E2E tests passed successfully on staging!\"}"

      - name: Notify E2E Failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"✅ Ruggine E2E tests failed on staging! Check the GitHub Actions logs for details.\"}"

  promote-to-prod:
    needs: e2e-test
    runs-on: ubuntu-24.04-arm
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
      
      - name: Get staging image tag
        run: |
          cd infra/overlays/staging
          IMAGE_TAG=$(kustomize build | grep "image:" | awk -F: '{print $3}')
          echo "PROMOTE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Update production image and commit
        run: |
          cd infra/overlays/prod
          kustomize edit set image ghcr.io/gurghet/ruggine:${{ env.PROMOTE_TAG }}
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add kustomization.yaml
          git commit -m "promote: update production to ruggine:${{ env.PROMOTE_TAG }}"
          git push

      - name: Notify Production Promotion Success
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"🚀 Ruggine successfully promoted to production with tag ${{ env.PROMOTE_TAG }}\"}"

      - name: Notify Production Promotion Failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"❌ Failed to promote Ruggine to production! Check the GitHub Actions logs for details.\"}"
